### ISSUE TITLE
Missing optimization from debootstrap

### ISSUE THREAD

**Issue by mickare** [tianon/docker-brew-ubuntu-core#120]
Hey,

the update script for the Ubuntu Dockerfiles is missing one optimization from the [debootstrap script](https://github.com/moby/moby/blob/master/contrib/mkimage/debootstrap).

https://github.com/moby/moby/blob/master/contrib/mkimage/debootstrap#L87-L90
```
# this file is one APT creates to make sure we don't "autoremove" our currently
# in-use kernel, which doesn't really apply to debootstraps/Docker images that
# don't even have kernels installed
rm -f "$rootfsDir/etc/apt/apt.conf.d/01autoremove-kernels"
```

Greetings,
mike

**Comment by tianon** [comment]
In the case of that script, it's being run on an unknown host where the contents of that file won't be useful or meaningful (since they'll automatically reference the host kernel, not anything that's necessarily relevant within Ubuntu or Debian).

In these images, that file comes directly from Canonical's builds, which happen on real Ubuntu hosts (and that file is reasonably harmless, especially for the container use case where the packages it references aren't typically even ever installed).
