### ISSUE TITLE
Builds should be deterministic for reproducibility

### ISSUE THREAD

**Issue by MarcoFalke** [tianon/docker-brew-ubuntu-core#128]
I tried to reproduce the image build locally (https://github.com/tianon/docker-brew-ubuntu-core/blob/master/update.sh), but the builds didn't seem to be deterministic.

Please let me know if there is a way to check that the published docker images are indeed derived from the Canonical "source of truth". I believe the most convenient way to check this is through deterministic builds.

**Comment by yosifkit** [comment]
The current process for updating the images is documented on the [README](https://github.com/tianon/docker-brew-ubuntu-core/tree/3742b406ffb023f272beabd7409507b9cec78079#scripts-to-prepare-updates-to-the-ubuntu-official-docker-images).  The `update.sh` script is only designed for downloading the latest (`current`) release from https://partner-images.canonical.com/core/ since they only keep a couple old versions (and they are not generated by us directly like the Debian artifacts).

You should be able to check the contents of any `dist-xxx` branch (like [amd64](https://github.com/tianon/docker-brew-ubuntu-core/tree/dist-amd64/bionic) for Bionic) and compare the files and shasums to the contents of the the partner-images directory for the same, but it looks like they have deleted the version that we used. :confused:

In that case you could just check the GPG signature of the sums files and have certainty the the tar.gz files were generated by Canonical.
