### ISSUE TITLE
checksum check

### ISSUE THREAD

**Issue by 030** [tianon/docker-brew-ubuntu-core#147]
https://partner-images.canonical.com/core/bionic/current/

I do not see any checksum verification in the docker image. One could check it by downloading the content inside of the container instead of using ADD

**Comment by yosifkit** [comment]
Since the images are `FROM scratch` there is nothing in the image to begin with (so we can't download a file or shasum or `gpg --verify`).  Verification is done on each branch when creating the `dist-*` branches via `update.sh` and it runs `verify.sh` and then commits (see also the jenkins [pipeline](https://doi-janky.infosiftr.net/job/tianon/job/update-ubuntu/) and [definition](https://github.com/docker-library/oi-janky-groovy/blob/a907001a5e85f52ed8a6da9e1e41574630785351/tianon/update-ubuntu-pipeline.groovy)):

https://github.com/tianon/docker-brew-ubuntu-core/blob/feb8e0e63d1f801039d9438335f4dc5fde077e1d/update.sh#L106
