### ISSUE TITLE
  Seems like `ubuntu:14.04` image has no setuid bit set on `/usr/bin/sudo`

### ISSUE THREAD

**Issue by 907th** [tianon/docker-brew-ubuntu-core#17]
I just installed `ubuntu:14.04` on VPS and fall with problem: when I create a new user and `su` it, then `sudo` stops working with message `sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set`.

Log:

``` bash
root@server:~/ejudge-docker# docker run -t -i ubuntu:14.04 bash
root@5c55117a425e:/# sudo ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@5c55117a425e:/# aduser ejudge
bash: aduser: command not found
root@5c55117a425e:/# adduser ejudge
Adding user `ejudge' ...
...
root@5c55117a425e:/# su ejudge
ejudge@5c55117a425e:/$ sudo ls
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
ejudge@5c55117a425e:/$ exit
root@5c55117a425e:/# sudo ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@5c55117a425e:/# which sudo
/usr/bin/sudo
root@5c55117a425e:/# ls -l /usr/bin/sudo
-rwxr-xr-x 1 root root 155008 Feb 10  2014 /usr/bin/sudo
```

**Comment by Nimeshka** [comment]
This happens when the permissions get changed. You can boot into Ubuntu recover mode and enter the following commands to get the root access back.

mount -o remount,rw /
mount --all
chown root:root /usr/bin/sudo
chmod 4755 /usr/bin/sudo
restart

I found this here : http://bitmapcake.blogspot.com/2014/08/linux-fixing-error-sudo-usr-bin-sudo-must-be-owned-by-uid.html

**Comment by Nikhilchopada** [comment]
i am apply this command but its OK work for me..so give me another solution
i use this command
mount -o remount,rw /
mount --all
chown root:root /usr/bin/sudo
chmod 4755 /usr/bin/sudo
restart
