### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by MarcelCoding** [tianon/docker-brew-ubuntu-core#195]
When i am using this image on my Raspberry PI (armhf) the time is always at 1970.
```
pi@pi: [~] → sudo docker run --rm -it --entrypoint /bin/bash ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
b3c478921ca1: Pull complete
f98985506b7e: Pull complete
dd88c4be5a76: Pull complete
Digest: sha256:fff16eea1a8ae92867721d90c59a75652ea66d29c05294e6e2f898704bdb8cf1
Status: Downloaded newer image for ubuntu:latest
root@8543aa82ff05:/# date
Thu Feb 26 08:20:11 UTC 1970
root@8543aa82ff05:/#
```

**Comment by tianon** [comment]
This is unfortunately the same underlying issue as https://github.com/tianon/docker-brew-ubuntu-core/issues/183 and https://github.com/tianon/docker-brew-ubuntu-core/issues/184.

In other words, in order to resolve this, your host needs to have installed:

- Docker version 19.03.9 or newer
- libseccomp version 2.4.2 or newer

**Comment by MarcelCoding** [comment]
@tianon 

![grafik](https://user-images.githubusercontent.com/34819524/99583399-bc654300-29e3-11eb-866c-c92e28638507.png)
ok the issue is because the Raspberry PI Package list doesn't contains a up to date version

But i have another question, why does the error only occurs on ubuntu and not on alpine and debain images. And a older version of the ubuntu image is also working fine.

**Comment by tianon** [comment]
> ok the issue is because the Raspberry PI Package list doesn't contains a up to date version

Yeah, you'll probably have to get an updated version from backports.

> But i have another question, why does the error only occurs on ubuntu and not on alpine and debain images. And a older version of the ubuntu image is working fine.

Yep, it's because `glibc` itself got updated to use the newer 64bit time syscalls on 32bit platforms, so Alpine won't see it (until a potentially newer version of `musl`, possibly in `alpine:edge` already?) and Debian *does* run into it in the (as yet unreleased) bullseye/testing version (and Debian unstable/sid).

**Comment by tianon** [comment]
Ah, and if you're running raspbian, I don't believe they do backports, so you'll probably need to pull it from testing/bullseye there anyhow.

**Comment by MarcelCoding** [comment]
Ok, tanks for your help!
