### ISSUE TITLE
CVE-2020-27350

### ISSUE THREAD

**Issue by rparini** [tianon/docker-brew-ubuntu-core#198]
Firstly, thanks for maintaining this image.

There is a CVE affecting `apt`: https://ubuntu.com/security/CVE-2020-27350, what is the timeline for the fixed version (2.0.2ubuntu0.2) to make it into the `ubuntu:20.04` image?

**Comment by tianon** [comment]
I can't speak for the Ubuntu security team (nor the folks at Canonical who maintain this image), but I can share this quote I received from the APT maintainers while performing the same update in Debian:

> you don't care about the security updates for apt and python-apt unless you run a service exposing the archive code to untrusted content ... And even then, I can still DoS you anyway

In other words, the attack vector here for containers is _even slimmer_ than on a desktop system, so I wouldn't expect this one to be fixed in the container images as a high priority. :sweat_smile:

(That being said, it definitely will be fixed - just maybe not with the same immediacy as something of a higher severity.)

**Comment by rparini** [comment]
OK, thanks for your quick response.  I'm happy if you want to close this issue or leave it open until that `apt` update is included

**Comment by rparini** [comment]
Version 2.0.2ubuntu0.2 is now in ubuntu:20.04 so I believe this is resolved
