### ISSUE TITLE
Repositories no longer have release files

### ISSUE THREAD

**Issue by awdm** [tianon/docker-brew-ubuntu-core#213]
Hi. I have an issue where I cannot execute `apt-get update` in order to install new software. I get the following error message:

    #8 4.736 E: The repository 'http://ports.ubuntu.com/ubuntu-ports yakkety Release' does no longer have a Release file.
    #8 4.736 E: The repository 'http://ports.ubuntu.com/ubuntu-ports yakkety-updates Release' does no longer have a Release file.
    #8 4.736 E: The repository 'http://ports.ubuntu.com/ubuntu-ports yakkety-backports Release' does no longer have a Release file.
    #8 4.736 E: The repository 'http://ports.ubuntu.com/ubuntu-ports yakkety-security Release' does no longer have a Release file.

I'm using the `armv7/armhf-ubuntu` image.

**Comment by awdm** [comment]
I was able to get it working by switching to Ubuntu 16.04.

**Comment by tianon** [comment]
I'm not sure what `armv7/armhf-ubuntu` is, but it isn't maintained out of this repository -- this repository is the source for https://hub.docker.com/_/ubuntu (and the ARMv7-specific variant of that would be https://hub.docker.com/r/arm32v7/ubuntu/).

The error you're running into is because yakkety (16.10) is EOL since 2017, so the packages aren't available from the official repositories anymore (see https://wiki.ubuntu.com/Releases).

**Comment by awdm** [comment]
Weird, the [DockerHub Repo](https://hub.docker.com/r/armv7/armhf-ubuntu) links to this GitHub. I'll definitely switch to the one you linked, since it's not five years old. Thanks for the heads up.
