### ISSUE TITLE
[Question] Why date is not updated when new version is created?

### ISSUE THREAD

**Issue by pando85** [tianon/docker-brew-ubuntu-core#219]
Hello guys,
I was checking [this commit](https://github.com/tianon/docker-brew-ubuntu-core/commit/b5a2c2a86e9dc83ef3a21551ea97e351697ed2d7) and the date is not updated in the file ` bionic/build-info.txt`. Should I use the hash if I want to fix to a specific version? or this is a bug.

**Comment by tianon** [comment]
If you check https://partner-images.canonical.com/oci/bionic/, the underlying tarball hasn't actually changed, which is why that date is still the same.

However, if you're looking for something that gives you the exact same bits, then yes, the (content addressable) image digest is the best way to ensure you get exactly the same bytes every time you pull the image.

**Comment by pando85** [comment]
Now it's totally clear, thank you for your answer.
