### ISSUE TITLE
start-stop-daemon on Ubuntu image id 5506de2b643b incorrectly reports process status

### ISSUE THREAD

**Issue by lnreeder** [tianon/docker-brew-ubuntu-core#27]
I tried to install tomcat7 on an ubuntu (image id 5506de2b643b)  following instructions on this blog post:  http://blog.trifork.com/2013/08/15/using-docker-to-efficiently-create-multiple-tomcat-instances.  I noticed that the init.d script did not return successfully although the tomcat java process was running and tomcat was working.   Further research showed that start-stop-daemon --test is not working correctly.   Here's a bash session showing the bug. 

```
#TOMCAT PID IS 43
root@a2cf26ade2a9:/# ps -eaf | grep tomcat7
tomcat7     43     1  0 14:06 ?        00:00:04 /usr/lib/jvm/java-7-oracle/bin/java -Djava.util.logging.config.file=/var/lib/tomcat7/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC -Djava.endorsed.dirs=/usr/share/tomcat7/endorsed -classpath /usr/share/tomcat7/bin/bootstrap.jar:/usr/share/tomcat7/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat7 -Dcatalina.home=/usr/share/tomcat7 -Djava.io.tmpdir=/tmp/tomcat7-tomcat7-tmp org.apache.catalina.startup.Bootstrap start

#PID FILE HAS CORRECT PID
root@a2cf26ade2a9:/#  cat /var/run/tomcat7.pid
43

#START-STOP-DAEMON --TEST REPORTS THAT IT WOULD START TOMCAT EVEN 
# THOUGH IT'S RUNNING 
root@a2cf26ade2a9:/#  start-stop-daemon --test --start --pidfile /var/run/tomcat7.pid --user tomcat7 --exec /usr/lib/jvm/java-7-oracle/bin/java
Would start /usr/lib/jvm/java-7-oracle/bin/java .

root@a2cf26ade2a9:/# echo $?
0
```

start-stop-daemon works as expected on my native Ubuntu install (Ubuntu 14.04.1 LTS)

**Comment by tianon** [comment]
Wow, this is an ancient bug that I completely lost track of. :disappointed: :heart:

I'm not sure what's going on here, but if it's still an issue, I'd recommend trying to narrow down what's different between the container environment and your host environment, and possibly filing an issue with `start-stop-daemon` itself (because we don't change anything in the configuration which might change its behavior besides having a smaller set of packages installed and no init system actively running). :confused:
