### ISSUE TITLE
Old libselinux breaks useradd on SELinux enabled host

### ISSUE THREAD

**Issue by welshjf** [tianon/docker-brew-ubuntu-core#29]
On an SELinux capable host (Fedora 20), the fact that /sys is mounted RO is supposed to signal to the container that SELinux is not supported on the inside, so it doesn't try to do things that won't work. Perhaps surprisingly, Ubuntu ships various things linked with libselinux, but the version on 12.04 lacks the above check.

    $ sudo docker run -ti ubuntu:12.04 
    root@b55e77ab9ef4:/# useradd test
    useradd: failure while writing changes to /etc/passwd
    root@b55e77ab9ef4:/# vipw
    vipw: setfscreatecon () failed: Permission denied
    vipw: /etc/passwd is unchanged

It thinks SELinux is enabled:

    root@b55e77ab9ef4:/# id -Z
    system_u:system_r:svirt_lxc_net_t:s0:c14,c127

For comparison, CentOS 7 on the same host, working correctly:

    $ sudo docker run -ti --rm centos:7 /bin/bash
    [root@cdc99d8acf68 /]# id -Z
    id: --context (-Z) works only on an SELinux-enabled kernel

RHEL 6 had the same problem; their fix was to update libselinux: https://bugzilla.redhat.com/show_bug.cgi?id=1112748

**Comment by tianon** [comment]
Sounds like http://packages.ubuntu.com/precise/libselinux1 is the package that needs to be updated for this -- probably worth filing a bug upstream: https://launchpad.net/ubuntu/+source/libselinux/+bugs (to see if they're even willing or able to pull in a newer version).

There's not much we can do from the Docker angle, since we just package "precise" as it exists today.

**Comment by welshjf** [comment]
Alright; I followed the "If you have any problems with or questions about this image" link here from the Docker page.

**Comment by welshjf** [comment]
Reported: https://bugs.launchpad.net/ubuntu/+source/libselinux/+bug/1424795
