### ISSUE TITLE
here, have some base images for older ubuntu versions

### ISSUE THREAD

**Issue by mcandre** [tianon/docker-brew-ubuntu-core#31]
I used debootstrap to generate base images for several older ubuntu versions:

https://registry.hub.docker.com/u/mcandre/docker-ubuntu/tags/manage/

Could we tag these into the tianon repository on Docker Hub?

**Comment by tianon** [comment]
I'm happy to see these available to folks, but since they're not officially supported by upstream, I don't think it'd be appropriate to offer them as official tags.  That being said, I think this issue is a decent pointer for people who are searching for such a thing to where they can find them.  Thanks! :+1:
