### ISSUE TITLE
Why ubuntu:latest cannot run with -d 

### ISSUE THREAD

**Issue by evagle** [tianon/docker-brew-ubuntu-core#34]
When run it with -d, it'll exits immediately。The stat is:
NTAINER ID        IMAGE               COMMAND             CREATED              STATUS                          PORTS               NAMES
0401c5294f2d        ubuntu:latest       "/bin/bash"         15 seconds ago       Exited (0) 14 seconds ago                           loving_nobel

**Comment by ohade** [comment]
It can, and it does.
The problem is that you are giving it a command that finishes and exit ("/bin/bash")
If you want your container to run in the background you need to give it something like 

docker run -d ubuntu:latest /bin/bash -c "while true; do echo 1; done"

and you will see the container running happily in the background

**Comment by tianon** [comment]
Indeed, that or something like this:
```console
$ docker run -dit --name test ubuntu bash
efc41a7a5fb55e6ad904586fab0d574294939301c87e0f31205bda15c96aeb32
$ docker attach test
root@efc41a7a5fb5:/# ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
root@efc41a7a5fb5:/# 
```
