### ISSUE TITLE
There's no easily accessible security policy

### ISSUE THREAD

**Issue by viraptor** [tianon/docker-brew-ubuntu-core#37]
I tried to find any kind of description for the official docker images regarding security updates. Unfortunately I could not find any. Thing's I'm looking for are:
- is there any commitment to update the docker tags when security updates come in
- is there any commitment to maximum lag behind security update repos
- is there any description of best practices on:
  - keeping own images fresh
  - upgrading manually in case the first two points are not valid

The only thing I could find is worrying information about apt-get in docker file (basically [don't run upgrade](https://docs.docker.com/articles/dockerfile_best-practices/#run))

It would be good if the image docker hub description included this info. Even if it's "you're on your own".

**Comment by yosifkit** [comment]
CVEs on applicable images are handled as quickly as fixes become available in the given distribution: https://github.com/docker-library/official-images/issues?utf8=%E2%9C%93&q=is%3Aissue+CVE.  There is no specific commitment to time, since most are dependent on packagers and release processes of the various Linux distributions; for example, it takes 3-10 days to migrate from Debian unstable to testing.

Here are the PRs that include Ubuntu updates: https://github.com/docker-library/official-images/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Alibrary%2Fubuntu.  Debian and Ubuntu images are updated at least once a month.  We encourage maintainers of other images to provide timely updates: https://github.com/docker-library/official-images#maintainership https://github.com/docker-library/official-images#commitment.

**Comment by tianon** [comment]
Indeed, we update on a fairly regular schedule as-is, and if there is a major vulnerability, we update ASAP.
