### ISSUE TITLE
Regenerate images after CVE-2015-7547

### ISSUE THREAD

**Issue by flx42** [tianon/docker-brew-ubuntu-core#41]
Hello,
I believe some images need to be recreated after the glibc fix here:
http://changelogs.ubuntu.com/changelogs/pool/main/e/eglibc/eglibc_2.19-0ubuntu6.7/changelog

By default with ubuntu:14.04 we get:
```
$ /lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Ubuntu EGLIBC 2.19-0ubuntu6.6) stable release version 2.19, by Roland McGrath et al.
```

But an upgrade is available for `libc6` and afterwards we have:
```
lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Ubuntu EGLIBC 2.19-0ubuntu6.7) stable release version 2.19, by Roland McGrath et al.
```

**Comment by tianon** [comment]
An update to address this is currently in-progress, and is being tracked for all images at https://github.com/docker-library/official-images/issues/1448. :+1:

Thanks!

**Comment by flx42** [comment]
Ah, sorry, the [Ubuntu page](https://hub.docker.com/_/ubuntu/) sent me here :)

**Comment by tianon** [comment]
Ah, that's a fair point!  We should probably update that to point at both https://github.com/docker-library/official-images/pulls?q=label%3Alibrary%2Fubuntu (up in the top section where right now it just links directly to the root of the official-images repo) and https://github.com/docker-library/official-images/issues?q=label%3Acve-tracker (down below in the "issues" section).

For reference (in case someone beats me to it because I don't have any cycles to tackle it right now), the files in question are https://github.com/docker-library/docs/blob/master/.template-helpers/template.md and https://github.com/docker-library/docs/blob/master/.template-helpers/user-feedback.md which would be the appropriate targets for pull requests.

**Comment by tianon** [comment]
https://github.com/docker-library/docs/pull/522 :+1:
