### ISSUE TITLE
Update apt lists to include universe packages

### ISSUE THREAD

**Issue by kevin-brown** [tianon/docker-brew-ubuntu-core#44]
This image previously would remove the apt lists, so it forced downstream images to call `apt-get update` before attempting to install any packages. That was removed in https://github.com/tianon/docker-brew-ubuntu-core/commit/2b010155860022ec68622ad17f9211c4e04373cb, as was the old call to `apt-get update`, which was so long ago that it's not relevant anymore.

So now this image includes support for universe packages, but the apt lists that are provided only cover the main packages. This is confusing for anyone who is used to running `apt-get install` to install standard packages (like `git-core`, for example), but then attempts to install a universe package only to see

> E: Unable to locate package foo

It's even more confusing because the [official sources.list file](https://github.com/docker-library/docs/tree/0f2497d8898080242de14a8b6e038e8ec7e300a6/ubuntu#etcaptsourceslist) includes universe, and it's not clear that you should call `apt-get update` to refresh those lists.

**Comment by tianon** [comment]
Arg, that's a regression in the tarballs.  I'm going to add back the lines which remove all the lists files, because it _is_ definitely recommended and necessary to run `apt-get update` before installing packages (ideally, with `RUN apt-get update && apt-get install -y ...` to ensure the lists are updated at package-install-time).
