### ISSUE TITLE
Fixed Ubuntu Xenial Image changed without a tag change

### ISSUE THREAD

**Issue by jmellor** [tianon/docker-brew-ubuntu-core#61]
2 weeks ago, I pulled ubuntu:xenial-20160713 image From hub.docker.com and got image id ac526a356ca4.  For this tag, this should be the same image id forever.
Today, I pulled the same image on a new machine, and received image id 42118e3df429.
I then pulled the same image on a third machine, and verified that the image id is the same 42118e3df429.

This appears to be an undocumented rebuild that should not be happening, and is clearly a stability issue for Users.  I do not want latest, as that is a rolling version, so I am consciously picking fully tagged images.

What bug was fixed?  Should I remove the 2-week-old image and re-download it to avoid a bug?  How do I identify whether products built using that image have a latent defect?  Is it normal to modify an exact product version without retagging it at a newer datestamp, and telling the Users about the bug?

**Comment by tianon** [comment]
The `ubuntu:xenial-20160713` image will always be based on the rootfs tarball provided by Canonical at https://partner-images.canonical.com/core/xenial/20160713/ -- that part will not change.  I _think_ what happened in this case is that we finally found what was causing #55 and fixed it, so that the unrelated core dump file in `/` should now be gone.

If you need _absolute_ consistency (down to the image ID level), you should be using pull-by-digest (ie, `ubuntu@sha256:c6674c44c6439673bf56536c1a15916639c47ea04c3d6296c5df938add67b54b` from https://github.com/docker-library/docs/blob/cc659441a2fbb2d82d37f14ec090277af002b619/ubuntu/tag-details.md#ubuntuxenial-20160713) or pulling the image and re-tagging it into a repo whose lifecycle you control directly, but for most folks that's likely going to be overkill. :smile:
