### ISSUE TITLE
Yakkety yakkety yakkety yakkety yakkety yakkety yakkety yakkety yak

### ISSUE THREAD

**Issue by graingert** [tianon/docker-brew-ubuntu-core#67]
Time for yakkety to become `latest`?

**Comment by tianon** [comment]
Nope -- `latest` is a bit of a misnomer in Docker; `default` probably would've been more accurate.  Since it's the tag that's used when no tag is specified, our `latest` tag corresponds to the "latest LTS release", which is currently `xenial` (and will be until at least 2018 unless Ubuntu changes their LTS policies before then).

See also "What's in this image?" from the image description (https://hub.docker.com/_/ubuntu/):

> The `ubuntu:latest` tag points to the "latest LTS", since that's the version recommended for general use.

**Comment by graingert** [comment]
Ah I see. Can you reopen this and I'll change the text to removing devel tag

**Comment by tianon** [comment]
The `devel` tag's target is scraped directly from Canonical's mirrors: https://github.com/tianon/docker-brew-ubuntu-core/blob/24efd22b0fb26f927452b06448097bb5a026ecbf/generate-stackbrew-library.sh#L14 (so will naturally go away when the new `devel` target is live)

```console
$ wget -qO- http://archive.ubuntu.com/ubuntu/dists/devel/Release | awk -F ': ' '$1 == "Codename" { print $2; exit }'
yakkety
```

**Comment by graingert** [comment]
@tianon ah I didn't see this. Is there an FAQ for this?

**Comment by tianon** [comment]
No, but I can/should update the description's `latest` note to also mention `devel`. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/docs/pull/730 :+1: :heart:
