### ISSUE TITLE
Locales is no longer in the base image for Xenial

### ISSUE THREAD

**Issue by goosemo** [tianon/docker-brew-ubuntu-core#82]
This has been in all the previous images but is now missing:
```
$ docker run --rm -ti ubuntu:16.04 bash -c locale-gen
bash: locale-gen: command not found
```

I also am at a loss tracking down changes/discussion of changes, in this repo. Where does the work actually get tracked?

**Comment by tianon** [comment]
We consume upstream's tarballs directly from https://partner-images.canonical.com/core/ (per their explicit request) -- Canonical decides what they contain, and they track issues/requests over at https://bugs.launchpad.net/cloud-images. :+1:

**Comment by goosemo** [comment]
Then they've taken it out of the base in the last few days, as the last one to have it is:
https://partner-images.canonical.com/core/xenial/20170328/ubuntu-xenial-core-cloudimg-amd64.manifest

these do not:
https://partner-images.canonical.com/core/xenial/20170331/ubuntu-xenial-core-cloudimg-amd64.manifest
https://partner-images.canonical.com/core/xenial/20170410/ubuntu-xenial-core-cloudimg-amd64.manifest


I've opened a ticket with them about this issue: https://bugs.launchpad.net/cloud-images/+bug/1682305

Will a new image be made automatically if they make another dist?

**Comment by dblackdblack** [comment]
@tianon would you consider putting the `16.04` and `xenial` docker tags on the old images until upstream fixes this? This has the potential to cause lots of people a lot of grief.

**Comment by tianon** [comment]
This is a change that upstream has made intentionally to reduce the size of their base images (see https://github.com/docker-library/official-images/issues/2856#issuecomment-294606986 and https://github.com/docker-library/official-images/issues/2863#issuecomment-294607003) -- as I am merely the proxy for their releases, I'm closing this in favor of the upstream ticket (https://bugs.launchpad.net/cloud-images/+bug/1682305).  If Canonical wants to add this back, I'm happy to update the images, but otherwise it is inappropriate for me to revert this change on their behalf.

It's not worth much, but my own opinion is that this is a positive change -- any packages included in the base image itself are packages that users cannot reasonably remove, so any packages that can be left out while still maintaining a usable base which Canonical is comfortable still calling "Ubuntu" is a good change in my mind.

Regardless, please make your case further to upstream (https://bugs.launchpad.net/cloud-images/+bug/1682305) if you feel they need to revert this change.  Thanks!
